### ISSUE TITLE
Can't test without Actionscript Classes

### ISSUE THREAD

**Issue by ifrancis** [Fabrice-Montfort/ezSTT_ANE#1]
Hi Fabrice, I like your ANE but I cannot test it within my own app without the missing AS3 classes:

import com.fabricemontfort.air.ezSTT;
import com.fabricemontfort.air.ezstt.STTEvent;
import com.fabricemontfort.air.ezstt.languages;

**Comment by Fabrice-Montfort** [comment]
Hello Francis,

I am pleased to see that this ANE is useful for your projects.
The 3 classes to which you refer are encapsulated in the ANE ezSTT.
Before you can use ezSTT, you must link the ANE to your project and then modify your XML description file.
A [tutorial](https://fabricemontfort.com/product/ezstt-ane-air-native-extension/) is available for the main IDEs compatible with AIR and AS3 (Link the extension with your project).

Tell me if you have a problem with this part.

**Comment by ifrancis** [comment]
Ok, got it working now.  I don't use an IDE to author and manually compile via the command line so I didn't look at those instructions.  I had to add the ANE to the library-path compiler options manually - I didn't know you could do that with an ANE directly. With other ANE's I've used (and created) I've used a separate SWC for the relevant Actionscript classes, hence the original question.  All good to know, thanks. It works really well BTW, just out of interest does it use the Google Cloud Speech API? Presumably it has to be online to work?... And on iOS, I presume you have to have Siri enabled (haven't been able to test this yet so asking the question) for this to work?

**Comment by Fabrice-Montfort** [comment]
Great news. I'm glad that it works on your work environment. Yes, adding an ANE for a command-line compilation is done in the same way as a SWC. Generally the SWCs supplied with the ANEs of the market are only a copy of the latter.

Concerning the native methods used, I used the functions provided by Google and Apple at the level of their OS. It is therefore not necessary to reference the project on any API (it works in the exact same way and with the exact same methods of their vocal assistants).

Finally, it can only work with an active internet connection. But according to my tests, it is not necessary to activate Siri on iOS. Indeed, Siri is an application provided by Apple whereas the framework used is available in low-side of the OS.

**Comment by MattTheNovice** [comment]
Hi Fabrice,
This is truly a fantastic piece of work. I know this is probably an old project for you but I am really interested in trying to integrate this project to aid me in the classroom (I am a teacher). I have linked the ANE and edited the XML descriptor file as directed by your website but I don't think it is picking up the STTEvent properly (error message - Type was not found or was not a compile-time constant: STTEvent). I believe I am having the same issue as ifrancis since I am using AS3 to code the project and Adobe Animate to compile my project. Any help would be greatly appreciated.
