### ISSUE TITLE
not working on samsung s4

### ISSUE THREAD

**Issue by bluelemonade** [Fabrice-Montfort/ezSTT_ANE#4]
Hello,

the ane didn't work on an my s4, it stop in less then a second, not usable!

regards

**Comment by Fabrice-Montfort** [comment]
Hi Bluelemonade,

Have you tested your compiled project on other devices (iOS and Android)? Does it work on these other devices with the same code?
Do you get an error message on the Samsung S4?
You can see messages with :
`
private var stt:ezSTT = ezSTT.instance;
stt.debug = true;
`
And then, your own code.

I never experienced this type of problem on a Samsung device.
Thank you for your comeback. We will try to see where the error is.

**Comment by bluelemonade** [comment]
I tried your apk, nothing own compiled.

**Comment by Fabrice-Montfort** [comment]
I'm looking for a Samsung Galaxy S4 to make some tests.

Maybe you can try to compile the demo project and then tell me if you have some error message ?

**Comment by bluelemonade** [comment]
ok, the demo code is for flashbuilder?

**Comment by Fabrice-Montfort** [comment]
You can use the example in any IDE. I use both IntelliJ IDEA and FlashBuilder 4.7 to compile this code.

Just make sure to link properly the ANE's and Starling/Feathers libraries
