### ISSUE TITLE
problem accessing the microphone outside of ezSTT

### ISSUE THREAD

**Issue by joonfromla** [Fabrice-Montfort/ezSTT_ANE#6]
I have tested ezSTT ANE and it works great. Thanks for opening speech recognition for Adobe air.

However, I am trying to integrate ezSTT_ANE into an application that already has a reference to the microphone for saving the user's speech into a bytearray.  I found that as soon as I instantiate my reference to the microphone like this:
var myMic:Microphone= Microphone.getMicrophone();

...then ezSTT_ANE will not function anymore.  I have tried instantiating myMic before ezSTT_ANE or the other way around, but the ezSTT_ANE still fails.  I have even tried to combine ezSTT_ANE with an AudioRecorder ANE by Distriqt, which doesn't seem to use Actionscript's Microphone.getMicrophone() at all, and still ezSTT fails.  

Perhaps myMic and ezSTT can both work in the same app if you added the ability for ezSTT to accept an audio file, like an mp3, as input.  Do you see that possibility?  Any ideas about other approaches I might take?

**Comment by Marcophono2** [comment]
Same question here. :)
Great ANE by the way. It was not so easy to bring it to work when inserting it into an existing AS program. I think another example code how to implement it into the standard class->function model. Don't let's hope that anyone would decompile your demo apk to find out how that works. ;)

Best regards
Marc
